name: ACAC
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.3

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.6.0
  location: ^6.0.2
  flutter_polyline_points: ^2.0.0
  provider: ^6.1.2
  geolocator: ^12.0.0
  intl: ^0.19.0
  modal_progress_hud_nsn: ^0.5.1
  pocketbase: ^0.18.1
  animated_text_kit: ^4.2.2
  url_launcher: ^6.2.6
  google_sign_in: ^6.2.1
  device_preview: ^1.1.0
  shared_preferences: ^2.2.3
  hooks_riverpod: ^2.5.1
  riverpod_generator: ^2.4.0
  riverpod_annotation: ^2.3.5
  riverpod: ^2.5.1
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  amplify_api: ^2.0.0
  amplify_auth_cognito: ^2.0.0
  amplify_authenticator: ^2.0.0
  amplify_flutter: ^2.0.0
  amplify_storage_s3: ^2.1.0
  flutter_secure_storage: ^9.2.2
  mobile_scanner: ^5.1.1
  pretty_qr_code: ^3.3.0
  delightful_toast: ^1.1.0
  qr_code_scanner: ^1.0.1
  flutter_windowmanager: ^0.2.0
  screen_protector: ^1.4.2
  internet_connection_checker_plus: ^2.5.0
  flutter_dotenv: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  amplify_lints: ^3.1.0
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - 'assets/'
    - images/
    - .env
    - env.text

  fonts:
    - family: helveticanowtext
      fonts:
        - asset: fonts/helveticanowtext-black-demo.ttf





        # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For

        #  style: italic
  #     - family: Trajan Pro
  #       fonts:
  #         - asset: fonts/TrajanPro.ttf
  #         - asset: fonts/TrajanPro_Bold.ttf
  #           weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
